version: "3.7"
networks:
  rails:
volumes:
  postgresql:
services:
  db:
    container_name: db_post
    image: postgres
    environment:
      - POSTGRES_PASSWORD=toor
      - POSTGRES_USER=root
      - POSTGRES_DB=stripe_example
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: always
    networks:
      - rails
    ports:
      - 4308:5432
  web:
    container_name: web
    build: .
    volumes:
      - "./src:/home/app/"
      # - type: bind
      #   source: ./src
      #   target: /home/app
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - rails
    environment:
      - DATABASE_PASSWORD=toor
      - DATABASE_NAME=hera
      - DATABASE_USER=root
      - DATABASE_PORT=3306
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=5
