version: "3"
networks:
  rails:
volumes:
  postgresql:
services:
  db:
    container_name: db_post
    image: postgres
    environment:
      - POSTGRES_PASSWORD=toor
      - POSTGRES_USER=root
      - POSTGRES_DB=stripe_example
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: always
    networks:
      - rails
    ports:
      - 4308:5432
  web:
    container_name: web
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - rails
    environment:
      - RAILS_ENV=development
