version: "3.7"
networks:
  rails:
volumes:
  postgresql:
  mysql:
services:
  db_mysql:
    image: mysql:5.7
    container_name: backend_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
  db_postgres:
    container_name: backend_postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=toor
      - POSTGRES_USER=root
      - POSTGRES_DB=stripe_example
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: always
    networks:
      - rails
    ports:
      - 4308:5432
  backend_rails:
    container_name: backend_rails
    build: .
    volumes:
      - "./src:/home/app/"
    ports:
      - "3000:3000"
    depends_on:
      - db_mysql
      - db_postgres
    links:
      - db_mysql
      - db_postgres
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}